FROM localhost/keycloak-extended:latest AS builder

ENV KC_HEALTH_ENABLED true

RUN /opt/keycloak/bin/kc.sh build

FROM localhost/keycloak-extended:latest

COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
