# Keycloak version -> Quarkus version mapping
# Format: minor = keycloak-version : quarkus-version
# Updated automatically by CI
nightly=999.0.0-SNAPSHOT:3.33.1
26.7=26.7.0:3.33.2.1
26.6=26.6.3:3.33.2.1
26.4=26.4.6:3.27.4.1
26.2=26.2.4:3.20.6
